### PR TITLE
Update ohm.py

### PR DESCRIPTION
**Pull request by Kirde001**
OBNOvite v sootvetstvii s trevovaniyami Korna

### CODE REVIEW

**Comment by Ice-hq** [comment]
> OBNOvite v sootvetstvii s trevovaniyami Korna

Poshel nahui

**Review by Ice-hq — COMMENTED** [review]
Kornpdr

**Comment by Ice-hq** [comment]
> OBNOvite v sootvetstvii s trevovaniyami Korna

**Comment by Kirde001** [comment]
> > OBNOvite v sootvetstvii s trevovaniyami Korna
> 
> Poshel nahui
Shingis lehenda, a korn vishe shingisa, smekaesh?

**Comment by Ice-hq** [comment]
> > > OBNOvite v sootvetstvii s trevovaniyami Korna
> > 
> > Poshel nahui
> Shingis lehenda, a korn vishe shingisa, smekaesh?
> 

EBay ty ahuel? Ty be stav korna s puzom na uroven shyngysa blyatb

**Comment by Kirde001** [comment]
> > > > OBNOvite v sootvetstvii s trevovaniyami Korna
> > > 
> > > 
> > > Poshel nahui
> > > Shingis lehenda, a korn vishe shingisa, smekaesh?
> 
> Ebat ty ahuel? Ty be stav korna s puzom na uroven shyngysa blyatb

No offence mister shingis

**Comment by Kirde001** [comment]
> > > > > > OBNOvite v sootvetstvii s trevovaniyami Korna
> > > > > 
> > > > > 
> > > > > Poshel nahui
> > > > > Shingis lehenda, a korn vishe shingisa, smekaesh?
> > > 
> > > 
> > > Ebat ty ahuel? Ty be stav korna s puzom na uroven shyngysa blyatb
> > 
> > 
> > No offence mister shingis
> 
> Blyatb huli zasoryaesh moyu stenu? Ya kak budu eto potom Yanochke otpravlyat? Pizdec nahui blyat

a ti ne otpravlyai

**Comment by Ice-hq** [comment]
> > > > > > > OBNOvite v sootvetstvii s trevovaniyami Korna
> > > > > > 
> > > > > > 
> > > > > > Poshel nahui
> > > > > > Shingis lehenda, a korn vishe shingisa, smekaesh?
> > > > 
> > > > 
> > > > Ebat ty ahuel? Ty be stav korna s puzom na uroven shyngysa blyatb
> > > 
> > > 
> > > No offence mister shingis
> > 
> > Blyatb huli zasoryaesh moyu stenu? Ya kak budu eto potom Yanochke otpravlyat? Pizdec nahui blyat
> 
> a ti ne otpravlyai

It's hard not to
But the borouuu

**Pull request closed without merging**
